<!DOCTYPE html><html lang="zh-CN"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>异常与错误 | Node.js API 文档</title>
  
  

    <link href="../../api/static/inject.css" rel="stylesheet"><link rel="icon" sizes="32x32" type="image/png" href="../../api/static/favicon.png"></head>

<body class="alt apidoc" id="page_api_item">
  <div id="api-section-errors">
    <div id="content" class="clearfix">

      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>异常与错误</h1>
          <div id="gtoc">
            <ul>
              <li>v16.16.0</li>
              <li>
                <a href="../errors.html#errors_exceptions_vs_errors" name="toc">返回上层文档</a>
              </li>

              <li class="picker-header">
    <a href="#">
        <span class="collapsed-arrow">►</span><span class="expanded-arrow">▼</span>
        其他版本
      </a>
    <div class="picker"><ol id="alt-docs">
    <li><a href="../../api/errors/exceptions_vs_errors.html">18.6.0</a></li><li><a href="">16.16.0</a></li><li><a href="../../api-v14/errors/exceptions_vs_errors.html">14.20.0</a></li>
</ol></div>
  </li>

              <li>
                <a href="http://api.nodejs.cn/" class="link-to-search">搜索</a>
              </li>
              <li>
                
                
              </li>

              <!-- <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/errors/#exceptions-vs-errors.md" rel="nofollow">提交修改</a>
              </li> -->
              <!-- <li>
                <a href="/gzh/">公众号</a>
              </li> -->
              <!-- <li class="biz_wrap" data-biz="api_item_nav">
                <a target="_blank" class="biz_title biz_link"></a>
              </li> -->
            </ul>
          </div>
          <hr>
        </header>

        <div id="apicontent">
          <div id="content_left"><p>JavaScript 异常是由于无效操作或作为 <code>throw</code> 语句的目标而抛出的值。
虽然不要求这些值是 <code>Error</code> 的实例或从 <code>Error</code> 继承的类，但 Node.js 或 JavaScript 运行时抛出的所有异常都将是 <code>Error</code> 的实例。</p><p class="">一些异常在 JavaScript 层是不可恢复的。
此类异常将始终导致 Node.js 进程崩溃。
示例包括 C++ 层中的 <code>assert()</code> 检查或 <code>abort()</code> 调用。</p></div>
          <div id="content_right"><p>A JavaScript exception is a value that is thrown as a result of an invalid
operation or as the target of a <code>throw</code> statement. While it is not required
that these values are instances of <code>Error</code> or classes which inherit from
<code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be
instances of <code>Error</code>.</p><p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions
will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code>
checks or <code>abort()</code> calls in the C++ layer.</p></div>
          <div></div>
        </div>

        <!-- <div id="biz_item" class="biz_wrap" data-biz="api_item">
          <a target="_blank" class="biz_link">
            <img class="biz_img" />
          </a>
        </div> -->
      </div>
    </div>
  </div>
  
  <div id="wxpaycode_box" style="display: none;">
    <div id="wxpaycode_img_box">
      <div id="wxpaycode_vip_tips">
        因经营维护成本巨大，
        <br>为了能提供更高质量的中文文档，
        <br>即日起将只对VIP会员开放。
        <br>扫码成为VIP会员，会员费用为<span id="wxpaycode_vip_money">199</span>元/年
      </div>
      <img id="wxpaycode_img">
    </div>
  </div>
  
  
  



    <script src="../../api/static/inject.js" defer=""></script></body></html>